hydra:
  hostname: 127.0.0.1
  public_port: 4444
  admin_port: 4445
  public_url: https://<< string::Server domain::^[a-Z0-9\.\-]{2,128}\.[a-Z0-9\.\-]{2,128}$::null >>
  admin_url: http://127.0.0.1:4445/admin

oauth:
  allowed_redirect_domains: << array::Allowed redirect domains::^https?:\/\/(?:(?:[-\w.])+(?:\.[a-zA-Z]{2,})+|localhost|(?:\d{1,3}\.){3}\d{1,3})(?::\d+)?(?:\/.*)?$::null >>
  allowed_scopes:<< array::Allowed oauth scopes::^[a-Z-0-9]$::null >>

services:
  launcher_proxy:
    port: 3000
  oauth_proxy:
    port: 3100

mcp_services:
  << object-array::MCP services::["name": "string::Service friendly name::[a-Z0-9\-_]{3,32}::null", "startup_command": "string::Service startup command::[a-Z0-9]{1,256}::null", "options": "array::Startup parameters::[a-Z0-9]{1,256}::null"] >>

users: << array::Authorized users::["email": "string::Emailaddress::[a-Z0-9]{5,256}::null", "password_hash": "bcrypt::Password::[a-Z0-9]{8,32}::null"] >>