---
graphql:
  max_size: 1048576
etcd:
  timeout: 30
  watch_timeout: 50
  startup_retry: 2
  host:
  - http://127.0.0.1:2379
  tls:
    verify: true
  prefix: /apisix
nginx_config:
  error_log_level: << string::Log level::null::"debug;info;warn;error" >>
  worker_processes: auto
  enable_cpu_affinity: false
  worker_rlimit_nofile: 20480
  worker_shutdown_timeout: 240s
  max_pending_timers: 16384
  max_running_timers: 4096
  user: root root
  event:
    worker_connections: 10620
  meta:
    lua_shared_dict:
      prometheus-metrics: 15m
      status-report: 1m
      standalone-config: 10m
  http:
    upstream:
      keepalive: 320
      keepalive_requests: 1000
      keepalive_timeout: 60s
    access_log_buffer: 16384
    keepalive_timeout: 60s
    client_header_timeout: 60s
    client_body_timeout: 60s
    client_max_body_size: 0
    send_timeout: 10s
    underscores_in_headers: 'on'
    real_ip_header: X-Real-IP
    real_ip_recursive: 'off'
    real_ip_from:
    - 127.0.0.1
    - 'unix:'
    access_log: logs/access.log
    proxy_ssl_server_name: true
    access_log_format: $remote_addr - $remote_user [$time_local] $http_host "$request"
      $status $body_bytes_sent $request_time "$http_referer" "$http_user_agent" $upstream_addr
      $upstream_status $upstream_response_time "$upstream_scheme://$upstream_host$upstream_uri"
    charset: utf-8
    access_log_format_escape: default
    variables_hash_max_size: 2048
    lua_shared_dict:
      mcp-session: 10m
      prometheus-metrics: 10m
      discovery: 1m
      jwks: 1m
      internal-status: 10m
      upstream-healthcheck: 10m
      worker-events: 10m
      lrucache-lock: 10m
      balancer-ewma: 10m
      balancer-ewma-locks: 10m
      balancer-ewma-last-touched-at: 10m
      etcd-cluster-health-check: 10m
      plugin-ai-rate-limiting: 10m
      plugin-ai-rate-limiting-reset-header: 10m
      plugin-limit-count: 10m
      plugin-limit-count-redis-cluster-slot-lock: 1m
      introspection: 10m
      plugin-limit-req: 10m
      plugin-limit-conn: 10m
      plugin-limit-req-redis-cluster-slot-lock: 1m
      plugin-limit-conn-redis-cluster-slot-lock: 1m
      tracing_buffer: 10m
      plugin-api-breaker: 10m
      access-tokens: 1m
      ext-plugin: 1m
      tars: 1m
      cas-auth: 10m
      ocsp-stapling: 10m
    enable_access_log: true
  stream_configuration_snippet: ''
  http_end_configuration_snippet: ''
  stream:
    access_log_format: $remote_addr [$time_local] $protocol $status $bytes_sent $bytes_received
      $session_time
    access_log_format_escape: default
    lua_shared_dict:
      tars-stream: 1m
      upstream-healthcheck-stream: 10m
      etcd-cluster-health-check-stream: 10m
      lrucache-lock-stream: 10m
      plugin-limit-conn-stream: 10m
      worker-events-stream: 10m
    enable_access_log: false
    access_log: logs/access_stream.log
  error_log: logs/error.log
  main_configuration_snippet: ''
  http_configuration_snippet: |
    # Custom static file serving
    server {
        listen 9280;
        root /static;
        
        location / {
          try_files $uri $uri/ =404;
        }
    }

  http_server_configuration_snippet: ''
  http_server_location_configuration_snippet: ''
  http_admin_configuration_snippet: ''
deployment:
  etcd:
    timeout: 30
    watch_timeout: 50
    startup_retry: 2
    host:
    - http://127.0.0.1:2379
    tls:
      verify: true
    prefix: /apisix
  role: traditional
  role_traditional:
    config_provider: etcd
  config_provider: etcd
  admin:
    enable_admin_cors: true
    admin_key:
    - name: admin
      role: admin
      key: << string::Apisix admin key::^[a-Z0-9\//-_]{32}$::null >>
    enable_admin_ui: true
    allow_admin:
    - 0.0.0.0/0
    admin_key_required: true
    admin_api_version: v3
    admin_listen:
      port: 9180
      ip: 0.0.0.0
plugins:
- cas-auth
- real-ip
- ai
- client-control
- proxy-control
- request-id
- zipkin
- ext-plugin-pre-req
- fault-injection
- mocking
- serverless-pre-function
- cors
- ip-restriction
- ua-restriction
- referer-restriction
- csrf
- uri-blocker
- request-validation
- chaitin-waf
- multi-auth
- openid-connect
- authz-casbin
- authz-casdoor
- wolf-rbac
- ldap-auth
- hmac-auth
- basic-auth
- jwt-auth
- jwe-decrypt
- key-auth
- consumer-restriction
- attach-consumer-label
- forward-auth
- opa
- authz-keycloak
- proxy-cache
- body-transformer
- ai-prompt-template
- ai-prompt-decorator
- ai-prompt-guard
- ai-rag
- ai-rate-limiting
- ai-proxy-multi
- ai-proxy
- ai-aws-content-moderation
- proxy-mirror
- proxy-rewrite
- workflow
- api-breaker
- limit-conn
- limit-count
- limit-req
- gzip
- traffic-split
- response-rewrite
- mcp-bridge
- ai-request-rewrite
- kafka-proxy
- grpc-transcode
- grpc-web
- http-dubbo
- public-api
- prometheus
- datadog
- lago
- loki-logger
- elasticsearch-logger
- echo
- loggly
- http-logger
- splunk-hec-logging
- ext-plugin-post-resp
- ext-plugin-post-req
- serverless-post-function
- openfunction
- openwhisk
- azure-functions
- aws-lambda
- example-plugin
- inspect
- tencent-cloud-cls
- clickhouse-logger
- file-logger
- udp-logger
- syslog
- rocketmq-logger
- kafka-logger
- redirect
- tcp-logger
- sls-logger
- google-cloud-logging
- skywalking-logger
- batch-requests  
- proxy-buffering      
stream_plugins:
- ip-restriction
- limit-conn
- mqtt-proxy
- syslog
plugin_attr:
  opentelemetry:
    trace_id_source: x-request-id
    set_ngx_var: false
    batch_span_processor:
      max_export_batch_size: 16
      drop_on_queue_full: false
      max_queue_size: 1024
      batch_timeout: 2
      inactive_timeout: 1
    collector:
      request_headers:
        Authorization: token
      address: 127.0.0.1:4318
      request_timeout: 3
    resource:
      service.name: APISIX
  proxy-mirror:
    timeout:
      send: 60s
      connect: 60s
      read: 60s
  prometheus:
    export_addr:
      port: 9091
      ip: 127.0.0.1
    metric_prefix: apisix_
    enable_export_server: true
    export_uri: /apisix/prometheus/metrics
  zipkin:
    set_ngx_var: false
  skywalking:
    report_interval: 3
    service_name: APISIX
    endpoint_addr: http://127.0.0.1:12800
    service_instance_name: APISIX Instance Name
  dubbo-proxy:
    upstream_multiplex_count: 32
  cors:
    allow_origins: << array::Cors allowed origins::^https?:\/\/(?:(?:[-\w.])+(?:\.[a-zA-Z]{2,})+|localhost|(?:\d{1,3}\.){3}\d{1,3})(?::\d+)?(?:\/.*)?$::null >>
  log-rotate:
    timeout: 10000
    max_size: -1
    enable_compression: false
    max_kept: 168
    interval: 3600
  inspect:
    delay: 3
    hooks_file: /usr/local/apisix/plugin_inspect_hooks.lua
apisix:
  standalone: "0"
  enable_debug: false
  router:
    ssl: radixtree_sni
    http: radixtree_host_uri
  proxy_mode: http
  resolver_timeout: 5
  enable_http2: true
  enable_admin: true
  admin_key:
  - name: admin
    role: admin
    key: << string::Apisix admin key::^[a-Z0-9\//-_]{32}$::null >>
  data_encryption:
    enable_encrypt_fields: true
    keyring: << string::Apisix encryption keyring::^[a-Z0-9]{16}$::null >>
  allow_admin:
  - 0.0.0.0/0
  events:
    module: lua-resty-events
  normalize_uri_like_servlet: false
  disable_sync_configuration_during_start: false
  show_upstream_status_in_response_header: false
  ssl:
    enable: true
    ssl_trusted_certificate: /etc/ssl/certs/ca-certificates.crt
    ssl_ciphers: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
    listen:
    - port: 9443
      enable_http3: false
    ssl_protocols: TLSv1.2 TLSv1.3
    ssl_session_tickets: false
  enable_resolv_search_opt: true
  enable_control: true
  delete_uri_tail_slash: false
  node_listen: 9080
  enable_dev_mode: false
  enable_reuseport: true
  enable_ipv6: true
  extra_lua_path: ''
  extra_lua_cpath: ''
  proxy_cache:
    cache_ttl: 10s
    zones:
    - name: disk_cache_one
      disk_size: 1G
      disk_path: /tmp/disk_cache_one
      cache_levels: '1:2'
      memory_size: 50m
    - name: memory_cache
      memory_size: 50m
  enable_server_tokens: true
...
