dsn: sqlite:///hydra-data/hydra.sqlite?_fk=true

urls:
  self:
    issuer: https://<< string::Server domain::^[a-Z0-9\.\-]{2,128}\.[a-Z0-9\.\-]{2,128}$::null >>/oauth
  login: https://<< string::Server domain::^[a-Z0-9\.\-]{2,128}\.[a-Z0-9\.\-]{2,128}$::null >>/oauth/login
  consent: https://<< string::Server domain::^[a-Z0-9\.\-]{2,128}\.[a-Z0-9\.\-]{2,128}$::null >>/oauth/consent

serve:
  public:
    port: 4444
  admin:
    port: 4445
    cors:
      enabled: true

log:
  level: << string::Log level::null::"debug;info;warn;error" >>
  leak_sensitive_values: true

secrets:
  system: 
    - << string::Hydra system secret::^[a-Z0-9\//-_]{32}$::null >>

oidc:
  dynamic_client_registration:
    enabled: true
    default_scope: << array::Hydra dynamic client registration default oauth scopes::^[a-Z-0-9]$::null >>

webfinger:
  oidc_discovery:
    client_registration_url: https://<< string::Server domain::^[a-Z0-9\.\-]{2,128}\.[a-Z0-9\.\-]{2,128}$::null >>/oauth/register